### ISSUE TITLE
ToDo Permalinks are opened in a new tab

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#183] opened 2022-09-05 14:09 UTC
When a ToDo is created from a post in Mattermost, a permalink is included in the title of the ToDo. 
Clicking the permalink is opening a new tab where he user is directed to the post (or opening in the browser when using desktop client). 
The user should be directed to the channel and post in the same tab.

**Steps**:  
- Make a post
- Click the action option and create a ToDo from the post
- Open the ToDo RHS and click the permalink that was created
**Expected**: The user is redirected to the channel and the permalink view of the post in the existing webapp client (browser tab they're using or desktop client)
**Observed**: A new browser tab is opened instead

**Note** This is also happening for me on the current production release if ToDo `v0.6.0`

**Comment by DHaussermann** [comment] 2022-09-12 15:11
Started a discussion here https://community.mattermost.com/core/pl/rzuzpwqkttnt38obtctqnmj9ky

**Comment by ayusht2810** [comment] 2024-04-10 14:28
@AayushChaudhary0001 Can you please test this issue? I tried to reproduce the issue on different versions but was not able to reproduce it.
cc: @DHaussermann

**Comment by AayushChaudhary0001** [comment] 2024-04-15 10:44
@ayusht2810 I have reproduced this issue and it looks similar to the issue #164 . Please verify it once.

**Comment by ayusht2810** [comment] 2024-04-15 10:44
@AayushChaudhary0001 closing this issue as it is a duplicate of issue #164, which is currently in progress.
cc: @DHaussermann

**Closed by ayusht2810** 2024-04-15 10:44 UTC
Labels: Type/Bug
