### ISSUE TITLE
"[x] add to thread" mode

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-todo#25] opened 2020-01-15 17:36 UTC
1) When creating a new TODO from a post (in the modal) add a checkbox [x] add this item to the conversation (thread?).
2. When the item is created, post a message to the thread - "Marked as Todo for @user"
3. When the item is popped, post a message to the thread "@user resolved ..."

cc @jwilander @aaronrothschild for further suggestions/edits.

**Comment by larkox** [comment] 2020-02-05 22:16
May I take this one?

**Comment by jwilander** [comment] 2020-02-06 14:59
Go for it @larkox !

**Comment by larkox** [comment] 2020-02-19 10:54
I have a good idea on how to do this, but the changes on the architecture with [this PR](https://github.com/mattermost/mattermost-plugin-todo/pull/27) will prove quite useful for dealing with this beautifully. Therefore, I would prefer to wait for that PR to be merged.

Regarding the solution, the idea would be to add the PostID to the Issue object. and whenever the issue is removed, if there is a postID, reply to the post.

**Comment by jwilander** [comment] 2020-02-23 14:21
That sounds reasonable to me @larkox 👍

**Closed** 2020-04-07 00:26 UTC
Labels: Difficulty/2:Medium, Help Wanted, Tech/Go, Tech/ReactJS, Type/Enhancement
