### ISSUE TITLE
Plugin does not error gracefully when expecting a username that is not provided

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#83] opened 2020-06-18 21:20 UTC
When using a slash command to send a user a ToDo item the plugin does not error gracefully and tell me no user is provided (as is the case with some system slash commands)

Steps:
- Enable ToDo
- type `/todo send  notauser`
- Send the command

**Observed**:  `Command with a trigger of '/todo' not found. Click here to send as a message.` and panic below which causes a crash.
**Expected**: The previous build without autocomplete tells me I need a user and provides help text. 
```
{"level":"debug","ts":1592514676.638249,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_update_active_status"}
{"level":"debug","ts":1592514677.561801,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_typing"}
{"level":"debug","ts":1592514677.5728362,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/teams/mkxtxnec8trmu8iiiygeucmfxo/commands/autocomplete_suggestions","request_id":"n88dtqyqobb1jmcqam1sezt3ey"}
{"level":"debug","ts":1592514677.9698281,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/teams/mkxtxnec8trmu8iiiygeucmfxo/commands/autocomplete_suggestions","request_id":"uet74jukjjrixysknekbm8p3je"}
{"level":"debug","ts":1592514678.1752052,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/teams/mkxtxnec8trmu8iiiygeucmfxo/commands/autocomplete_suggestions","request_id":"dpyqs5u4aj8zmcqf9eizyw6rah"}
{"level":"debug","ts":1592514687.6415071,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_typing"}
{"level":"debug","ts":1592514687.663142,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/commands/execute","request_id":"83zy13c81ir88rkkxj5fdd34ha"}
{"level":"debug","ts":1592514687.6678872,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: index out of range [0] with length 0","plugin_id":"com.mattermost.plugin-todo"}
{"level":"debug","ts":1592514687.667972,"caller":"plugin/hclog_adapter.go:53","msg":"","plugin_id":"com.mattermost.plugin-todo"}
{"level":"debug","ts":1592514687.6680052,"caller":"plugin/hclog_adapter.go:53","msg":"goroutine 117 [running]:","plugin_id":"com.mattermost.plugin-todo"}
{"level":"debug","ts":1592514687.6680372,"caller":"plugin/hclog_adapter.go:53","msg":"main.(*Plugin).runSendCommand(0xc0000962a0, 0xc000042120, 0x2, 0x2, 0xc000168000, 0x3, 0x4, 0xc000042100)","plugin_id":"com.mattermost.plugin-todo"}
{"level":"debug","ts":1592514687.668073,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-todo/server/command.go:118 +0x72a","plugin_id":"com.mattermost.plugin-todo"}
```

**Comment by DHaussermann** [comment] 2020-06-18 21:34
@iomodo based on the location of the panic and testing ToDo v0.2.0 (which still fails gracefully), It would seem that this introduced by the addition of autocomplete to the plugin and unrelated to server or webapp changes for 5.24.

Can you please confirm this and advise if a broader change is needed for the infrastructure to handle cases where plugins could fail in this way?

**Comment by larkox** [comment] 2020-06-19 07:36
The problem here I am almost sure that is a common effort between the user and Autocomplete to put extra spaces between the arguments. Will look into it.

**Comment by hanzei** [comment] 2020-06-19 07:43
Is this a duplicate of https://github.com/mattermost/mattermost-plugin-todo/issues/70?

**Closed** 2020-07-01 12:30 UTC
Labels: Type/Bug
